### ISSUE TITLE
Cannot compile with node 0.12?

### ISSUE THREAD

**Issue by Redsandro** [hideo55/node-murmurhash3#8]
On node `0.10`, everything is fine.
But on node `0.12` I get compile errors.

```
$ npm install murmurhash3
/
> murmurhash3@0.2.3 install /var/www/app/node_modules/murmurhash3
> node-gyp rebuild


Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/app/node_modules/murmurhash3
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "murmurhash3"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! murmurhash3@0.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the murmurhash3@0.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the murmurhash3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls murmurhash3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/app/npm-debug.log
```

`npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'murmurhash3' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink /usr/bin/node
5 warn package.json group-by@0.0.1 No repository field.
6 warn package.json qtree@0.1.0 No repository field.
7 warn package.json qtree@0.1.0 No README data
8 warn package.json to-function@1.2.1 repo should probably be repository.
9 verbose install murmurhash3 is installed as 0.2.3
10 silly cache add args [ 'murmurhash3@0.2.3', null ]
11 verbose cache add spec murmurhash3@0.2.3
12 silly cache add parsed spec { raw: 'murmurhash3@0.2.3',
12 silly cache add   scope: null,
12 silly cache add   name: 'murmurhash3',
12 silly cache add   rawSpec: '0.2.3',
12 silly cache add   spec: '0.2.3',
12 silly cache add   type: 'version' }
13 verbose addNamed murmurhash3@0.2.3
14 silly addNamed semver.valid 0.2.3
15 silly addNamed semver.validRange 0.2.3
16 silly mapToRegistry name murmurhash3
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry uri https://registry.npmjs.org/murmurhash3
20 verbose addNameVersion registry:https://registry.npmjs.org/murmurhash3 not in flight; fetching
21 verbose request uri https://registry.npmjs.org/murmurhash3
22 verbose request no auth needed
23 info attempt registry request try #1 at 13:49:53
24 verbose request id e132d9a337a7cb2a
25 http request GET https://registry.npmjs.org/murmurhash3
26 http 200 https://registry.npmjs.org/murmurhash3
27 silly get cb [ 200,
27 silly get   { date: 'Thu, 30 Apr 2015 11:49:54 GMT',
27 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
27 silly get     etag: '"CAY4XG8KBDJO58LN0UXJ0GZ8M"',
27 silly get     'content-type': 'application/json',
27 silly get     'cache-control': 'max-age=60',
27 silly get     'content-length': '27851',
27 silly get     'accept-ranges': 'bytes',
27 silly get     via: '1.1 varnish',
27 silly get     age: '0',
27 silly get     'x-served-by': 'cache-ams4124-AMS',
27 silly get     'x-cache': 'MISS',
27 silly get     'x-cache-hits': '0',
27 silly get     'x-timer': 'S1430394594.020977,VS0,VE185',
27 silly get     vary: 'Accept',
27 silly get     'keep-alive': 'timeout=10, max=50',
27 silly get     connection: 'Keep-Alive' } ]
28 verbose get saving murmurhash3 to /home/redsandro/.npm/registry.npmjs.org/murmurhash3/.cache.json
29 silly mapToRegistry name murmurhash3
30 silly mapToRegistry using default registry
31 silly mapToRegistry registry https://registry.npmjs.org/
32 silly mapToRegistry uri https://registry.npmjs.org/murmurhash3
33 verbose addRemoteTarball https://registry.npmjs.org/murmurhash3/-/murmurhash3-0.2.3.tgz not in flight; adding
34 verbose addRemoteTarball [ 'https://registry.npmjs.org/murmurhash3/-/murmurhash3-0.2.3.tgz',
34 verbose addRemoteTarball   'decaf21205d5cc2ef75f89b40c6ef01972967d70' ]
35 info retry fetch attempt 1 at 13:49:54
36 info attempt registry request try #1 at 13:49:54
37 http fetch GET https://registry.npmjs.org/murmurhash3/-/murmurhash3-0.2.3.tgz
38 http fetch 200 https://registry.npmjs.org/murmurhash3/-/murmurhash3-0.2.3.tgz
39 silly fetchAndShaCheck shasum decaf21205d5cc2ef75f89b40c6ef01972967d70
40 verbose addTmpTarball /tmp/npm-4677-1d906837/registry.npmjs.org/murmurhash3/-/murmurhash3-0.2.3.tgz not in flight; adding
41 verbose addTmpTarball already have metadata; skipping unpack for murmurhash3@0.2.3
42 silly cache afterAdd murmurhash3@0.2.3
43 verbose afterAdd /home/redsandro/.npm/murmurhash3/0.2.3/package/package.json not in flight; writing
44 verbose afterAdd /home/redsandro/.npm/murmurhash3/0.2.3/package/package.json written
45 silly install resolved [ { name: 'murmurhash3',
45 silly install resolved     version: '0.2.3',
45 silly install resolved     description: 'Node binding of MurmurHash3',
45 silly install resolved     repository:
45 silly install resolved      { type: 'git',
45 silly install resolved        url: 'https://github.com/hideo55/node-murmurhash3' },
45 silly install resolved     bugs: { url: 'https://github.com/hideo55/node-murmurhash3/issues' },
45 silly install resolved     homepage: 'http://hideo55.github.com/node-murmurhash3/',
45 silly install resolved     keywords: [ 'hash', 'murmurhash' ],
45 silly install resolved     author: { name: 'Hideaki Ohno', email: 'hide.o.j55@gmail.com' },
45 silly install resolved     dependencies: {},
45 silly install resolved     devDependencies: { mocha: '1.8.1' },
45 silly install resolved     main: './lib/murmurhash3.js',
45 silly install resolved     engines: { node: '>=0.6.13' },
45 silly install resolved     scripts: { test: 'mocha -R spec test.js', install: 'node-gyp rebuild' },
45 silly install resolved     gypfile: true,
45 silly install resolved     _id: 'murmurhash3@0.2.3',
45 silly install resolved     dist:
45 silly install resolved      { shasum: 'decaf21205d5cc2ef75f89b40c6ef01972967d70',
45 silly install resolved        tarball: 'http://registry.npmjs.org/murmurhash3/-/murmurhash3-0.2.3.tgz' },
45 silly install resolved     _from: 'murmurhash3@0.2.3',
45 silly install resolved     _npmVersion: '1.2.25',
45 silly install resolved     _npmUser: { name: 'hide_o_55', email: 'hide.o.j55@gmail.com' },
45 silly install resolved     maintainers: [ [Object] ],
45 silly install resolved     directories: {},
45 silly install resolved     _shasum: 'decaf21205d5cc2ef75f89b40c6ef01972967d70',
45 silly install resolved     _resolved: 'https://registry.npmjs.org/murmurhash3/-/murmurhash3-0.2.3.tgz' } ]
46 info install murmurhash3@0.2.3 into /var/www/app
47 info installOne murmurhash3@0.2.3
48 verbose installOne of murmurhash3 to /var/www/app not in flight; installing
49 verbose lock using /home/redsandro/.npm/_locks/murmurhash3-dfef5e06a1bf67b6.lock for /var/www/app/node_modules/murmurhash3
50 silly install write writing murmurhash3 0.2.3 to /var/www/app/node_modules/murmurhash3
51 silly cache addNamed cb murmurhash3@0.2.3
52 verbose unbuild node_modules/murmurhash3
53 info preuninstall murmurhash3@0.2.3
54 info uninstall murmurhash3@0.2.3
55 verbose unbuild rmStuff murmurhash3@0.2.3 from /var/www/app/node_modules
56 info postuninstall murmurhash3@0.2.3
57 silly gentlyRm /var/www/app/node_modules/murmurhash3 is being purged from base /var/www/app
58 verbose gentlyRm don't care about contents; nuking /var/www/app/node_modules/murmurhash3
59 silly vacuum-fs purging /var/www/app/node_modules/murmurhash3
60 silly vacuum-fs quitting because other entries in /var/www/app/node_modules
61 verbose tar unpack /home/redsandro/.npm/murmurhash3/0.2.3/package.tgz
62 verbose tar unpacking to /var/www/app/node_modules/murmurhash3
63 silly gentlyRm /var/www/app/node_modules/murmurhash3 is being purged
64 verbose gentlyRm don't care about contents; nuking /var/www/app/node_modules/murmurhash3
65 silly gunzTarPerm modes [ '755', '644' ]
66 silly gunzTarPerm extractEntry package.json
67 silly gunzTarPerm extractEntry .npmignore
68 silly gunzTarPerm extractEntry test.js
69 silly gunzTarPerm extractEntry History.md
70 silly gunzTarPerm extractEntry Readme.md
71 silly gunzTarPerm extractEntry binding.gyp
72 silly gunzTarPerm extractEntry lib/murmurhash3.js
73 silly gunzTarPerm extractEntry src/MurmurHash3.cpp
74 silly gunzTarPerm extractEntry src/MurmurHash3.h
75 silly gunzTarPerm extractEntry src/node_murmurhash3.cc
76 info preinstall murmurhash3@0.2.3
77 silly install resolved []
78 verbose about to build /var/www/app/node_modules/murmurhash3
79 info build /var/www/app/node_modules/murmurhash3
80 verbose linkStuff [ false,
80 verbose linkStuff   false,
80 verbose linkStuff   false,
80 verbose linkStuff   '/var/www/app/node_modules' ]
81 info linkStuff murmurhash3@0.2.3
82 verbose linkBins murmurhash3@0.2.3
83 verbose linkMans murmurhash3@0.2.3
84 verbose rebuildBundles murmurhash3@0.2.3
85 info install murmurhash3@0.2.3
86 verbose unsafe-perm in lifecycle true
87 info murmurhash3@0.2.3 Failed to exec install script
88 verbose unlock done using /home/redsandro/.npm/_locks/murmurhash3-dfef5e06a1bf67b6.lock for /var/www/app/node_modules/murmurhash3
89 verbose stack Error: murmurhash3@0.2.3 install: `node-gyp rebuild`
89 verbose stack Exit status 1
89 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
89 verbose stack     at EventEmitter.emit (events.js:110:17)
89 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
89 verbose stack     at ChildProcess.emit (events.js:110:17)
89 verbose stack     at maybeClose (child_process.js:1015:16)
89 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
90 verbose pkgid murmurhash3@0.2.3
91 verbose cwd /var/www/app
92 error Linux 3.13.0-24-generic
93 error argv "/usr/bin/node" "/usr/bin/npm" "install" "murmurhash3"
94 error node v0.12.2
95 error npm  v2.7.4
96 error code ELIFECYCLE
97 error murmurhash3@0.2.3 install: `node-gyp rebuild`
97 error Exit status 1
98 error Failed at the murmurhash3@0.2.3 install script 'node-gyp rebuild'.
98 error This is most likely a problem with the murmurhash3 package,
98 error not with npm itself.
98 error Tell the author that this fails on your system:
98 error     node-gyp rebuild
98 error You can get their info via:
98 error     npm owner ls murmurhash3
98 error There is likely additional logging output above.
99 verbose exit [ 1, true ]
100 verbose unbuild node_modules/murmurhash3
101 info preuninstall murmurhash3@0.2.3
102 info uninstall murmurhash3@0.2.3
103 verbose unbuild rmStuff murmurhash3@0.2.3 from /var/www/app/node_modules
104 info postuninstall murmurhash3@0.2.3
105 silly gentlyRm /var/www/app/node_modules/murmurhash3 is being purged from base /var/www/app
106 verbose gentlyRm don't care about contents; nuking /var/www/app/node_modules/murmurhash3
107 silly vacuum-fs purging /var/www/app/node_modules/murmurhash3
108 silly vacuum-fs quitting because other entries in /var/www/app/node_modules
```

**Comment by hideo55** [comment]
`murmurhash3@0.2.3` is too old.
Please use latest version.

**Comment by Redsandro** [comment]
Sorry, I saw the package lock. I retried with latest version. Same problem.

I think the culprit might be node-gyp tho. When I install node 0.11 or 0.12 node-gyp fails, in 0.10 it works, also the latest version.
